Adding job feed + perfomance disscussion
algeriatech/dz-community-bot pull request #15
Opened 2017-01-14 21:37 UTC by houssem-yahiaoui

This PR have two part : 

**## The first one :** 

Possible tested solution for issue #9 proposed by Riad, consist of returning max of top 5 jobs from dyalna.com web site,

The command will return top 5 objects within the scope of those 2 options: 

1. If we ask the bot about jobs in a channel different then #jobs, the bot will ask the user to ask her over #jobs channel.
2. Via direct message.

Last i want to mention that the 'fallback' option over the showcasing  options are required by slack, the why is that sometimes, if we do ask the bot for some stuff then not being **physically** present over slack a **notification** will be returned as part of the UX that slack use, so the fallback will give us a nicely looking fallback message of what's happening over **slack** now.

<img width="341" alt="benefits of fallback over slack attachments" src="https://cloud.githubusercontent.com/assets/15380057/21958234/dee6866a-daa9-11e6-8838-a39886e89c65.png">

**## Second one :** 

some loops enhancements regarding some perfomance over the data.body.forEach, i've replaced it with a normal loop taking on consideration this [jsperf benchmark.](https://jsperf.com/for-loop-test-more)

2017-01-14 22:00 UTC, IOAyman requested changes

2017-01-14 22:00 UTC, IOAyman commented on .env.sample
> +-# Generated at https://my.slack.com/services/new/bot
What are these for? 😕

2017-01-14 22:00 UTC, IOAyman commented on package.json
> +    "install": "^0.8.4",
What're you doing with that package?

2017-01-14 22:00 UTC, IOAyman commented on package.json
> +    "npm": "^4.1.1",
How about this one?

2017-01-14 22:02 UTC, houssem-yahiaoui commented on package.json
> +    "npm": "^4.1.1",
nothing really probably from that package removal i made.

2017-01-14 22:06 UTC, IOAyman commented
You might want to regenerate the `yarn.lock` file as well @houssem-yahiaoui ;)

2017-01-14 22:07 UTC, houssem-yahiaoui commented
Yes, i'm on it :)

2017-01-14 22:16 UTC, IOAyman commented
Concerning that performance test, I'm curious if there's a write-up digging more about those tests?
Another question is, are those tests for browsers only? Or does it include node as well 😕

2017-01-14 22:30 UTC, houssem-yahiaoui commented
I guess the test was made in a web page to begin with and jsperf act on benchmarking regarding a a web page, but i do believe even if two ecosystem are different (web/node) we  the test was made over chrome using the v8 engine so it is there present, probably same thing applied to node v8 ! but that just me.

2017-01-14 22:33 UTC, IOAyman approved these changes
LGTM 👍

Closes #9

2017-01-14 22:36 UTC, merged

2017-01-14 22:38 UTC, IOAyman commented
Let's take the conversation over the the [Slack](algeriatech.slack.com)

2017-01-15 12:35 UTC, youknowriad commented on src/controllers/dyalna.js
> +        for (let i = 0, len = data.body.length; i <= len; i++) {
For each is better in my opinion

2017-01-15 12:36 UTC, youknowriad commented on src/controllers/dyalna.js
> +        if (msg.channel == 'C3NRY5JP2' || msg.event == 'direct_message') {
I think there's a constant for direct_message

2017-01-15 12:39 UTC, youknowriad commented on src/controllers/dyalna.js
> +                'title_link': `${ data.body[i].url }`,
I would rather use the Dyalna Jobs link (to thank Dyalna Jobs for the centralized API :), I know it's my website )

2017-02-13 09:48 UTC, Ingeskhaled commented
Bonjour les jeunes !! par ce message je m'adresse à Yahioui Houssem. Je te prise de répondre au téléphone d'ici ce soir sinon je commencerais par déposer plainte pour vol qualifié.

Je sais très bien que tu vois mes appels  !!

2017-02-13 12:07 UTC, Ingeskhaled commented
Bonjour les gars, j'ai publié un message par erreur  tout à l'heure
merci de ne pas prendre en compte